version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/choria-io/go-config

    environment:
      GO111MODULE: "on"

    steps:
      - checkout

      - run: go mod download
      - run: go get github.com/onsi/ginkgo/ginkgo
      - run: go get -u honnef.co/go/tools/cmd/staticcheck
      - run: go get -u github.com/client9/misspell/cmd/misspell
      - run: go list ./...|xargs staticcheck
      - run: find . -type f -name "*.go" | grep -v "/vendor/" | xargs misspell -error -locale US
      - run: ginkgo -r .
